### ISSUE TITLE
Modal issue missing label

### ISSUE THREAD

**Issue by hotgeart** [SimpleBasicElements/Elements#3]
I didn't test all of it, but there's a big issue, you didn't put an aria-labelledby.

So when the modal will open the screen reader will speak about the input directly without mention the title, so you don't know what the form is about.

    <dialog aria-labelledby="dialog-label">
        <title id="dialog-label">

**Comment by Grafikart** [comment]
I don't plan to include this in the library. The user is responsible for handling this attribute. In some situation (if the modal is displayed after a click on a button) I don't think the label is necessary. 

I can still add a note on the readme if you want.

**Comment by hotgeart** [comment]
If there's a way to make the life of the user easier I intend to do so. But I understand your pov. It's your call.
